#!/bin/sh

echo "*****Running check code******"

git stash -q --keep-index

./gradlew goJF
./gradlew lintGradle
./gradlew fixGradleLint
./gradlew generateGradleLintReport


status=$?

git stash pop -q

echo "*****Done with check code******"

exit $status
